export const stockPlayerCharacters = [
  {
    playerName: "Zoe",
    charName: "Steph La'Pod",
    charConcept: "Brash rockabilly squid tattoo artist",
    charImage: "https://i.ibb.co/SXQL7Jx/steph.png",
    attributes: {
      brawn: 3,
      agility: 2,
      intelligence: 1,
      wit: 2,
      charm: 2,
      presence: 3,
    },
    chosenMasteries: ["Biology", "Perform", "Spacewise"],
    chosenProficiencies: ["Melee", "Empathy", "Lying"],
  },
  {
    playerName: "Jon",
    charName: "Melvin",
    charConcept: "Urkelian conspiracy theorist & mad scientist",
    charImage: "https://i.ibb.co/TMTq9GT/melvin.png",
    attributes: {
      brawn: 1,
      agility: 2,
      intelligence: 4,
      wit: 2,
      charm: 2,
      presence: 2,
    },
    chosenMasteries: ["Computers", "Engineering"],
    chosenProficiencies: [
      "Explosives",
      "Firearms",
      "Investigation",
      "Piloting",
      "Persuasion",
      "Spacewise",
      "Telekenesis",
    ],
  },
  {
    playerName: "Taylor",
    charName: "M.A.H.",
    charConcept: "Robotic maid / Intergalactic Intelligence Officer",
    charImage: "https://i.ibb.co/wNcHWqy/MAH.png",
    attributes: {
      brawn: 2,
      agility: 2,
      intelligence: 3,
      wit: 2,
      charm: 3,
      presence: 1,
    },
    chosenMasteries: ["Investigation", "Perform"],
    chosenProficiencies: [
      "Engineering",
      "Lying",
      "Melee",
      "Sneaking",
      "Spacewise",
    ],
  },
  {
    playerName: "Hayley",
    charName: "ghost",
    charConcept: "Vapour creature",
    charImage: "https://i.ibb.co/jfKvFT7/ghost.png",
    attributes: {
      brawn: 1,
      agility: 3,
      intelligence: 2,
      wit: 2,
      charm: 2,
      presence: 3,
    },
    chosenMasteries: ["Sneaking", "Telepathy"],
    chosenProficiencies: ["Empathy", "Lying", "Persuasion", "Telekinesis"],
  },
];
